---
title: "Report from buoydata data pull"
output: html_document
params: 
  sameDim: NA  
  dimFields: NA
  col_name_added: NA
  col_name_removed: NA
  removed_IDs: NA
  added_IDs: NA
  removed_rows: NA
  added_rows: NA
date: "`r Sys.time()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Do the two data sets have the name number of buoys and the same number of variables?

```{r samedim, echo = FALSE}
paste0("Are the table dimensions the same: ",params$sameDim)
```

```{r samedim2, echo = FALSE}
message("Table differences:")
params$dimFields
```


## Field names added or removed

```{r fieldsnms, echo = FALSE}
print(paste0("Fields added: ",params$col_name_added))
print(paste0("Fields removed: ",params$col_name_removed))
```


## Buoys added or removed

```{r IDs, echo = FALSE}

print(paste0("IDs added: ",params$added_IDs))
print(paste0("IDs removed: ",params$removed_IDs))
```

## Added Rows

```{r addedrows, echo = FALSE}
if (is.na(params$added_rows)) {
  message("No rows added")
} else {
  params$added_rows |>
    gt::gt()
}

```


## Removed Rows

```{r removedrows, echo = FALSE}
if (is.na(params$removed_rows)) {
  message("No rows removed")
} else {
  params$removed_rows |>
    gt::gt()
}
```


## Links to repos:

* [buoydata](https://github.com/NOAA-EDAB/buoydata)
